void lancerCommandes();
void verifstat(char*);
void aleatoire(int*);
int creerProccessusFils();
void choixProgramme();
void lancerStats();
void lancerStatique();
void lancerDynamique();
void lancerInteractif();
